name: Link Check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check links
        uses: lycheeverse/lychee-action@v1
        with:
          args: >-
            --base .
            --verbose
            --no-progress
            --accept 200,206,429
            README.md
            sections/*.md
            CONTRIBUTING.md
